### ISSUE TITLE
Recommendation for resizing non-last dimension arrays?

### ISSUE THREAD

**Issue by biona001** [JuliaArrays/ElasticArrays.jl#14]
I wish to resize a square matrix into another square matrix. What is the recommended style for doing this? I figured this is the best place to ask.

The following approach as suggested in [this post](https://stackoverflow.com/questions/41781621/resizing-a-matrix) leads to segmentation fault errors. 
```
M = rand(100, 100);
Mvec = vec(M);
Mnew = Base.ReshapedArray(Mvec, (1000, 1000), ())
```

**Comment by oschulz** [comment]
Hey @biona001, your example doesn't seem to involve ElasticArrays.jl at all.

As for the segfault: Obviously, you can't reshape a 100x100 array into an 1000x1000 array. Usually, one would call `reshape()` instead of calling the `ReshapedArray` constructor directly - but I don't think it should segfault. This involves Julia `Base`, however, not `ElasticArrays`.

**Comment by oschulz** [comment]
Closing this here, I opened JuliaLang/julia#32923 instead.
