### ISSUE TITLE
Confused by parent()

### ISSUE THREAD

**Issue by garrison** [JuliaArrays/ElasticArrays.jl#24]
There are many tests that call `parent(E)`, but I am unsure what is meant by this.  It seems that the fallback `parent(a::AbstractArray) = a` is being called, so this is equivalent to `E`.  Do the tests assume this is actually pointing to `E.data`?  That was what I first thought when looking at the code.

**Comment by oschulz** [comment]
Good point, @garrison - we used to have

```julia
Base.parent(A::ElasticArray) = A.data
```

@colinxs, you removed that inPR #21, citing concerns over functions in `LinearAlgebra` depending on `size(A) == size(parent)`.

I think we should bring `parent` back, if possible - it kind of was a breaking change, and it's a natural way for the user to get the underlying array: `ElasticArray` is effectively a reshaped view, and `Base.ReshapedArray` defines parent the same way:

```julia
A = view(rand(10), :)
B = reshape(A, 2, 5)::Base.ReshapedArray
parent(B) === A
```

@colinxs, if this works for `Base.ReshapedArray`, why would it cause trouble for `ElasticArray` with `LinearAlgebra`?

With parent gone, the tests that use it are definitely not meaningful at the moment.

**Comment by oschulz** [comment]
@colinxs, any thoughts on this?

**Comment by oschulz** [comment]
Ping @colinxs

**Comment by oschulz** [comment]
@colinxs, if you have no objections, I'll re-introduce `parent()`

**Comment by oschulz** [comment]
There's `_parent` now for the tests - I'll hold off on re-introducing `parent()` for now. Using `E.data` directly should be considered the "official" way to get the underlying array.

**Comment by colinxs** [comment]
Hey all, looks like I'm late to the party.

I distinctly remember removing `parent(.)` because it broke some functions in `LinearAlgebra`:
```
julia> e=ElasticArray{Float64}(undef, 2, 2);

julia> inv(e)
2×2 ElasticArray{Float64,2,1,Array{Float64,1}}:
 NaN  NaN
 NaN  NaN

julia> Base.parent(x::ElasticArray) = x.data;

julia> inv(e)
ERROR: MethodError: no method matching Array{Float64,1}(::ElasticArray{Float64,2,1,Array{Float64,1}})
Closest candidates are:
  Array{Float64,1}(::AbstractArray{S,N}) where {T, N, S} at array.jl:541
  Array{Float64,1}() where T at boot.jl:424
  Array{Float64,1}(::UndefInitializer, ::Int64) where T at boot.jl:405
  ...
Stacktrace:
 [1] convert(::Type{Array{Float64,1}}, ::ElasticArray{Float64,2,1,Array{Float64,1}}) at ./array.jl:533
 [2] inv(::ElasticArray{Float64,2,1,Array{Float64,1}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/dense.jl:771
 [3] top-level scope at REPL[9]:
```

Of course, this works for views:
```
julia> x = rand(2,2,3);

julia> y = view(x, :, :, 1);

julia> inv(y)
2×2 Array{Float64,2}:
  2.86746  -0.732495
 -1.27941   1.43739
```

The error comes from [this line](https://github.com/JuliaLang/julia/blob/927c24f900130fb7d27a353cd22b4654c1d6336b/stdlib/LinearAlgebra/src/dense.jl#L813). 

It looks like this is happening because we tried to be too "performant". `LinearAlgebra.inv!(LinearAlgebra.lu(y::SubArray))` makes a copy and returns an `Array` while `LinearAlgebra.inv!(LinearAlgebra.lu(y::ElasticArray))` returns an `ElasticArray`. On the next line `parent(.)` gets called and you get the above error because `ndims(parent(E::ElasticArray)) != ndims(E:ElasticArray)`.

It seems to me that this is more of a bug in `LinearAlgebra` than in `ElasticArrays`. The docs for `parent(.)` are lacking in detail and don't specify the requirement that `ndims(parent(A::AbstractArray)) == ndims(A::AbstractArray)`.

I think the best way forward is to file an issue against `LinearAlgebra` and get some feedback. We/I may be wrong, or maybe this is indeed a bug. If we have to guarantee `ndims(parent(A::AbstractArray)) == ndims(A::AbstractArray)` then either we 1) make `convert(::{T<:ElasticArray}, ::ElasticArray)` return an `Array` copy OR keep my changes, which defaults to `parent(A) = A` in Base.

Making `parent(::ElasticArray)` return a properly-dimensioned copy is kind defeating the whole point of `ElasticArrays`, so hopefully we can avoid doing that. I don't like slow code.

**Comment by oschulz** [comment]
Thanks for the explanation, @colinxs - no `parent()`, then. :-)

**Comment by colinxs** [comment]
Haha no worries. Sorry I've been a bit MIA. 

I'm really not sure what the correct behavior of `parent(.)` is, nor the expectations of `LinearAlgebra` It would be good to get a solid answer so that we can do the "right thing". Not having bugs >> fast code. Since you're the owner of this repo would you mind opening an issue over on the Julia repo so we can figure out the proper course? I'm happy to help.

**Comment by oschulz** [comment]
I agree that it would be nice to have a clearer definition on the expected behavior of `parent`. Could you maybe open that issue though, @colinxs ? You dove way deeper than me into the LinearAlgebra implementation issues with `parent`, you can probably describe it better. I'm really a bit confused about this, because with a view, the dimensionality of the parent can also be very different.

As far as ElasticArrays is concerned, I just realized that I should never have used `parent()` for this - because clearly, the appropriate function to use is `vec()`! I'll add that now ...
